server:
  port: 20002
  servlet:
    session:
      cookie:
        name: indi_oauth_center_session
spring:
  application:
    name: auth-center-local
    #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
   # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.142.176:3306/indi_database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    platform: mysql

  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
#      - classpath:/templates
      file:E:\CCX3\trunk\05 Source\resources\oauth-center\templates
    request-context-attribute: request

  # 设置静态文件路径，js,css等
  mvc:
    locale: zh_CN
    static-path-pattern: /static/**
  resources:
    static-locations: file:E:\CCX3\trunk\05 Source\resources\oauth-center\static\
# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.cloud.oauth.center.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 通用 Mapper 配置
mapper:
  identity: MYSQL
  not-empty: false
  mappers: indi.cloud.oauth.center.base.core.Mapper

eureka:
  client:
    security:
      user: register
      password: qaz2019
    serviceUrl:
      defaultZone: http://47.102.142.176:8001/eureka/ #注册中心的注册地址(注册到8002， 系统数据同步到8001)
    healthcheck:
      enabled: true #开启健康检查
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #将Instance ID设置为IP:端口的形式
    lease-renewal-interval-in-seconds: 100 #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 200  # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        security.oauth2: DEBUG

# 默认的重定向地址
# 目前仅支持一个站点
# 后续可以改进为，根据client_id，跳转到指定的站点
ccx:
  default_redirect_uri: http://127.0.0.1:9010
  message:
    user-not-found: 用户名或密码不正确。
    user-disabled: 用户已停用。
    user-expired: 用户已过期。
    institution-disabled: 机构已停用。
    institution-expired: 机构已过期。



